/**
 * @module CMFPaymentForm
 *
 * Headless React component that implements the complete CMF payment flow.
 *
 * Uses semantic HTML with `className` on each element so integrators can
 * style it with any framework (Tailwind, CSS Modules, styled-components, etc.).
 * Does NOT import any UI library -- the component is functional without styles.
 *
 * ## Flow
 *
 * 1. **Search**: The user enters their email or phone registered with CMF
 * 2. **OTP**: CMF sends a verification code to the chosen channel
 * 3. **Verification**: The user enters the code to confirm identity
 * 4. **Cards**: The user's CMF cards are displayed
 * 5. **Quotas**: The user selects a payment plan (installments or full payment)
 * 6. **Payment**: The payment is processed with CMF
 *
 * @example
 * ```tsx
 * import { CMFPaymentForm } from '@panama-payments/cmf/react';
 *
 * <CMFPaymentForm
 *   total={150.00}
 *   userName="Juan Perez"
 *   description="Compra en Mi Tienda"
 *   onSuccess={(receiptNumber) => {
 *     router.push(`/confirmation/${receiptNumber}`);
 *   }}
 * />
 * ```
 */

import React, { useState, useEffect, useCallback } from 'react';
import { useCMFCustomer } from '../hooks/useCMFCustomer.js';
import { useCMFOtp } from '../hooks/useCMFOtp.js';
import { useCMFQuotas } from '../hooks/useCMFQuotas.js';
import { useCMFPayment } from '../hooks/useCMFPayment.js';
import { CMFOtpChannel } from '../../types.js';
import type { CMFQuota, CMFProduct } from '../../types.js';
import { CMFDocumentType } from '../../types.js';

/**
 * Props for the `CMFPaymentForm` component.
 *
 * @example
 * ```tsx
 * <CMFPaymentForm
 *   total={150.00}
 *   userName="Juan Perez"
 *   description="Compra en Mi Tienda - Orden #12345"
 *   onSuccess={(receiptNumber) => confirmOrder(orderId, { cmfReceiptNumber: receiptNumber })}
 *   onError={(msg) => toast.error(msg)}
 *   className="mt-4 rounded-lg border p-6"
 * />
 * ```
 */
export interface CMFPaymentFormProps {
  /**
   * Total purchase amount in USD.
   * Used to calculate available financing plans.
   */
  total: number;

  /**
   * Name of the end user (customer of the merchant).
   * Included in CMF transactions.
   */
  userName: string;

  /**
   * Purchase description shown in the CMF confirmation email.
   *
   * @example 'Compra en Mi Tienda - Orden #12345'
   */
  description: string;

  /**
   * Callback invoked when the payment is processed successfully.
   * Receives the unique receipt number from CMF for your database.
   *
   * @param receiptNumber - Unique transaction ID generated by CMF
   */
  onSuccess: (receiptNumber: string) => void;

  /**
   * Optional callback invoked when an error occurs at any step.
   * If not provided, errors are only shown in the component UI.
   *
   * @param error - Human-readable error message
   */
  onError?: (error: string) => void;

  /**
   * Additional CSS class for the root container element.
   * Allows applying external styles without overriding internal structure.
   */
  className?: string;

  /**
   * Backend API base URL for CMF endpoints.
   * The component builds endpoint URLs by appending paths to this base.
   *
   * @default '/api/cmf'
   */
  apiBase?: string;
}

/** Internal form steps */
type FormStep = 'search' | 'otp' | 'cards' | 'quotas' | 'paying' | 'success';

/** Internal type for a card with its quota plans */
interface CardWithQuotas {
  product: CMFProduct;
  cardIndex: number;
  quotas: CMFQuota[];
}

/**
 * Headless component implementing the complete CMF payment flow.
 *
 * All steps are managed internally -- no external state management required.
 * For advanced integrations with Zustand or other state managers, use the
 * individual hooks (`useCMFCustomer`, `useCMFOtp`, `useCMFQuotas`, `useCMFPayment`).
 *
 * Each HTML element has a `className` with `cmf-` prefix for easy styling.
 *
 * @example
 * ```tsx
 * function CheckoutPage() {
 *   const total = useCartTotal();
 *
 *   return (
 *     <section className="payment-section">
 *       <h2>Pagar con CMF</h2>
 *       <CMFPaymentForm
 *         total={total}
 *         userName={user.name}
 *         description={`Orden #${orderId}`}
 *         onSuccess={(receiptNumber) => {
 *           confirmOrder(orderId, { cmfReceiptNumber: receiptNumber });
 *         }}
 *         onError={(msg) => toast.error(msg)}
 *         className="mt-4 rounded-lg border p-6"
 *       />
 *     </section>
 *   );
 * }
 * ```
 */
export function CMFPaymentForm({
  total,
  userName,
  description,
  onSuccess,
  onError,
  className = '',
  apiBase = '/api/cmf',
}: CMFPaymentFormProps) {
  const [step, setStep] = useState<FormStep>('search');
  const [activeChannel, setActiveChannel] = useState<'email' | 'phone'>('email');
  const [searchValue, setSearchValue] = useState('');
  const [selectedProduct, setSelectedProduct] = useState<CMFProduct | null>(null);
  const [selectedQuota, setSelectedQuota] = useState<CMFQuota | null>(null);

  const customer = useCMFCustomer({ endpoint: `${apiBase}/customer` });
  const otp = useCMFOtp({
    sendEndpoint: `${apiBase}/otp/send`,
    verifyEndpoint: `${apiBase}/otp/verify`,
  });
  const quotas = useCMFQuotas({ endpoint: `${apiBase}/quotas` });
  const payment = useCMFPayment({ endpoint: `${apiBase}/pay` });

  // Load quotas when a product is selected
  useEffect(() => {
    if (selectedProduct && total > 0) {
      quotas.getQuotas(selectedProduct.customerProductId, total);
      setStep('quotas');
    }
  }, [selectedProduct]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleSendOtp = useCallback(async () => {
    if (!searchValue.trim()) return;
    const ch = activeChannel === 'email' ? CMFOtpChannel.Email : CMFOtpChannel.Phone;
    await otp.sendOtp(ch, searchValue.trim());
    if (!otp.error) {
      setStep('otp');
    } else {
      onError?.(otp.error);
    }
  }, [activeChannel, searchValue, otp, onError]);

  const handleVerifyOtp = useCallback(
    async (code: string) => {
      await otp.verifyOtp(code);
      if (otp.step === 'done') {
        // After OTP verified, search for customer to get products
        await customer.search(CMFDocumentType.Cedula, searchValue);
        if (customer.products.length > 0) {
          if (customer.products.length === 1) {
            setSelectedProduct(customer.products[0]);
          } else {
            setStep('cards');
          }
        }
      } else if (otp.error) {
        onError?.(otp.error);
      }
    },
    [otp, customer, searchValue, onError],
  );

  const handleSelectProduct = useCallback((product: CMFProduct) => {
    setSelectedProduct(product);
  }, []);

  const handlePay = useCallback(async () => {
    if (!selectedProduct || !selectedQuota) return;

    setStep('paying');

    const isNormalPayment = selectedQuota.uniqueCode === 'normal-payment';
    const receiptNumber = `ORDER-${Date.now()}${Math.floor(Math.random() * 1000)}`;

    if (isNormalPayment) {
      const card = selectedProduct.customerAccountCards[0];
      if (!card) {
        setStep('quotas');
        onError?.('No card available for this product');
        return;
      }
      await payment.pay({
        mode: 'normal',
        cardNumber: card.card,
        amount: total,
        receiptNumber,
        description,
        userName,
      });
    } else {
      await payment.pay({
        mode: 'quotas',
        customerProductId: selectedProduct.customerProductId,
        accountNumber: selectedProduct.productAccount,
        uniqueCode: selectedQuota.uniqueCode,
        amount: total,
        receiptNumber,
        description,
        userName,
      });
    }

    if (payment.result) {
      setStep('success');
      onSuccess(receiptNumber);
    } else {
      setStep('quotas');
      onError?.(payment.error ?? 'Payment failed');
    }
  }, [selectedProduct, selectedQuota, total, userName, description, payment, onSuccess, onError]);

  // ── Render: Search ────────────────────────────────────────────────────────

  if (step === 'search') {
    return (
      <div className={`cmf-payment-form cmf-step-search ${className}`}>
        <h3 className="cmf-title">Pagar con CMF</h3>
        <p className="cmf-subtitle">
          Ingresa el email o telefono registrado en tu cuenta CMF para continuar.
        </p>

        <div className="cmf-channel-tabs" role="tablist">
          <button
            role="tab"
            aria-selected={activeChannel === 'email'}
            className={`cmf-tab ${activeChannel === 'email' ? 'cmf-tab--active' : ''}`}
            onClick={() => setActiveChannel('email')}
            type="button"
          >
            Correo electronico
          </button>
          <button
            role="tab"
            aria-selected={activeChannel === 'phone'}
            className={`cmf-tab ${activeChannel === 'phone' ? 'cmf-tab--active' : ''}`}
            onClick={() => setActiveChannel('phone')}
            type="button"
          >
            Telefono (WhatsApp)
          </button>
        </div>

        <div className="cmf-field">
          <label htmlFor="cmf-search-input" className="cmf-label">
            {activeChannel === 'email' ? 'Correo electronico' : 'Telefono (8 digitos, sin +507)'}
          </label>
          <input
            id="cmf-search-input"
            type={activeChannel === 'email' ? 'email' : 'tel'}
            className="cmf-input"
            placeholder={activeChannel === 'email' ? 'usuario@gmail.com' : '61234567'}
            value={searchValue}
            onChange={(e) => setSearchValue(e.target.value)}
            disabled={otp.isLoading}
            autoComplete={activeChannel === 'email' ? 'email' : 'tel'}
          />
        </div>

        {(customer.error || otp.error) && (
          <p className="cmf-error" role="alert">
            {customer.error || otp.error}
          </p>
        )}

        <button
          className="cmf-button cmf-button--primary"
          onClick={handleSendOtp}
          disabled={otp.isLoading || !searchValue.trim()}
          type="button"
        >
          {otp.isLoading ? 'Enviando codigo...' : 'Enviar codigo de verificacion'}
        </button>
      </div>
    );
  }

  // ── Render: OTP Verification ──────────────────────────────────────────────

  if (step === 'otp') {
    return (
      <div className={`cmf-payment-form cmf-step-otp ${className}`}>
        <h3 className="cmf-title">Verificacion de identidad</h3>
        <p className="cmf-subtitle">
          Ingresa el codigo enviado a tu {activeChannel === 'email' ? 'correo' : 'WhatsApp'}.
        </p>

        <OtpInput
          onVerify={handleVerifyOtp}
          isLoading={otp.isLoading}
          error={otp.error}
          onCancel={() => {
            otp.reset();
            setStep('search');
          }}
          onResend={() => {
            const ch = activeChannel === 'email' ? CMFOtpChannel.Email : CMFOtpChannel.Phone;
            otp.sendOtp(ch, searchValue.trim());
          }}
        />
      </div>
    );
  }

  // ── Render: Card Selection ────────────────────────────────────────────────

  if (step === 'cards') {
    return (
      <div className={`cmf-payment-form cmf-step-cards ${className}`}>
        <h3 className="cmf-title">Selecciona tu tarjeta CMF</h3>
        <p className="cmf-subtitle">Elige la tarjeta con la que deseas pagar.</p>

        <ul className="cmf-card-list" role="listbox" aria-label="Tarjetas CMF disponibles">
          {customer.products.map((product, index) => (
            <li key={product.customerProductId} role="option" aria-selected={selectedProduct === product}>
              <button
                className="cmf-card-item"
                onClick={() => handleSelectProduct(product)}
                type="button"
              >
                <span className="cmf-card-name">
                  {product.customerAccountCards[0]?.maskedCard ?? 'Tarjeta CMF'}
                </span>
                <span className="cmf-card-product">{product.productName}</span>
              </button>
            </li>
          ))}
        </ul>
      </div>
    );
  }

  // ── Render: Quota Selection ───────────────────────────────────────────────

  if (step === 'quotas') {
    const normalPaymentQuota: CMFQuota = {
      customerProductId: selectedProduct?.customerProductId ?? '',
      uniqueCode: 'normal-payment',
      descriptionPlan: 'Pago completo',
      interestDescription: null,
      fixedRateLoanId: 'normal',
      loanTerm: 1,
      effectiveInterestPct: 0,
      downPayment: 0,
      productPrice: total,
      frequencyType: 'Pago unico',
      totalCreditAmount: total,
      pendingTotalCreditAmount: null,
      requestedAmount: total,
      interestAmount: 0,
      totalInterestSum: 0,
      interestPct: 0,
      monthlyQuota: total,
      annualEffectiveRate: 0,
      totalInterest: null,
      capitalValue: total,
      paidAmount: 0,
      balanceAmount: total,
      startDate: new Date().toISOString(),
      finishDate: null,
      lastModifiedDate: new Date().toISOString(),
      downPaymentPercentage: 0,
    };

    const allOptions = [normalPaymentQuota, ...quotas.quotas];

    return (
      <div className={`cmf-payment-form cmf-step-quotas ${className}`}>
        <h3 className="cmf-title">Elige tu plan de pago</h3>

        {customer.products.length > 1 && (
          <button
            className="cmf-link"
            onClick={() => {
              setSelectedProduct(null);
              setSelectedQuota(null);
              quotas.reset();
              setStep('cards');
            }}
            type="button"
          >
            Ver todas las tarjetas
          </button>
        )}

        {selectedProduct && (
          <p className="cmf-selected-card">
            Tarjeta: <strong>{selectedProduct.customerAccountCards[0]?.maskedCard}</strong>
          </p>
        )}

        {quotas.isLoading ? (
          <p className="cmf-loading" role="status">Cargando planes de pago...</p>
        ) : (
          <ul className="cmf-quota-list" role="listbox" aria-label="Planes de pago disponibles">
            {allOptions.map((quota) => (
              <li
                key={quota.uniqueCode}
                role="option"
                aria-selected={selectedQuota?.uniqueCode === quota.uniqueCode}
              >
                <button
                  className={`cmf-quota-item ${
                    selectedQuota?.uniqueCode === quota.uniqueCode ? 'cmf-quota-item--selected' : ''
                  }`}
                  onClick={() => setSelectedQuota(quota)}
                  type="button"
                >
                  {quota.uniqueCode === 'normal-payment' ? (
                    <>
                      <span className="cmf-quota-term">Pago completo</span>
                      <span className="cmf-quota-amount">${total.toFixed(2)}</span>
                      <span className="cmf-quota-interest">Sin intereses</span>
                    </>
                  ) : (
                    <>
                      <span className="cmf-quota-term">{quota.loanTerm} cuotas</span>
                      <span className="cmf-quota-amount">
                        ${quota.monthlyQuota.toFixed(2)}/mes
                      </span>
                      <span className="cmf-quota-interest">
                        {quota.effectiveInterestPct > 0
                          ? `${quota.effectiveInterestPct}% efectivo anual`
                          : 'Sin intereses'}
                      </span>
                    </>
                  )}
                </button>
              </li>
            ))}
          </ul>
        )}

        {selectedQuota && (
          <div className="cmf-quota-summary">
            <p>
              <strong>Plan seleccionado:</strong>{' '}
              {selectedQuota.uniqueCode === 'normal-payment'
                ? `Pago completo de $${total.toFixed(2)}`
                : `${selectedQuota.loanTerm} cuotas de $${selectedQuota.monthlyQuota.toFixed(2)}`}
            </p>
            {selectedQuota.uniqueCode !== 'normal-payment' && (
              <p>
                <strong>Total a pagar:</strong> ${selectedQuota.totalCreditAmount.toFixed(2)}
              </p>
            )}
          </div>
        )}

        {payment.error && (
          <p className="cmf-error" role="alert">{payment.error}</p>
        )}

        <button
          className="cmf-button cmf-button--primary"
          onClick={handlePay}
          disabled={!selectedQuota || payment.isLoading}
          type="button"
        >
          {payment.isLoading ? 'Procesando pago...' : 'Pagar con CMF'}
        </button>
      </div>
    );
  }

  // ── Render: Processing ────────────────────────────────────────────────────

  if (step === 'paying') {
    return (
      <div className={`cmf-payment-form cmf-step-paying ${className}`}>
        <p className="cmf-loading" role="status" aria-live="polite">
          Procesando tu pago con CMF...
        </p>
        <p className="cmf-loading-sub">Por favor no cierres ni recargues esta pagina.</p>
      </div>
    );
  }

  // ── Render: Success ───────────────────────────────────────────────────────

  if (step === 'success') {
    return (
      <div className={`cmf-payment-form cmf-step-success ${className}`}>
        <h3 className="cmf-title">Pago exitoso!</h3>
        <p className="cmf-subtitle">
          Tu pago con CMF fue procesado correctamente. Recibiras un email de confirmacion de CMF.
        </p>
      </div>
    );
  }

  return null;
}

// ── Internal OTP Input subcomponent ─────────────────────────────────────────

/**
 * Internal OTP code input component.
 * @internal
 */
function OtpInput({
  onVerify,
  isLoading,
  error,
  onCancel,
  onResend,
}: {
  onVerify: (code: string) => Promise<void>;
  isLoading: boolean;
  error: string | null;
  onCancel: () => void;
  onResend: () => void;
}) {
  const [code, setCode] = useState('');

  return (
    <>
      <div className="cmf-field">
        <label htmlFor="cmf-otp-code" className="cmf-label">
          Codigo de verificacion
        </label>
        <input
          id="cmf-otp-code"
          type="text"
          inputMode="numeric"
          className="cmf-input cmf-input--otp"
          placeholder="000000"
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
          maxLength={6}
          autoComplete="one-time-code"
          disabled={isLoading}
        />
      </div>

      {error && (
        <p className="cmf-error" role="alert">{error}</p>
      )}

      <div className="cmf-button-group">
        <button
          className="cmf-button cmf-button--secondary"
          onClick={onCancel}
          type="button"
        >
          Cancelar
        </button>
        <button
          className="cmf-button cmf-button--primary"
          onClick={() => onVerify(code)}
          disabled={isLoading || code.length < 4}
          type="button"
        >
          {isLoading ? 'Verificando...' : 'Verificar codigo'}
        </button>
      </div>

      <div className="cmf-resend">
        <button
          className="cmf-link"
          onClick={onResend}
          disabled={isLoading}
          type="button"
        >
          No recibiste el codigo? Reenviar
        </button>
      </div>
    </>
  );
}
