/**
 * @module useCMFPayment
 *
 * React hook for processing CMF payments (installment or normal card charge).
 *
 * The hook calls your backend, which processes the payment using `CMFClient`.
 * On success, CMF automatically sends a confirmation email to the customer.
 */

import { useState, useCallback } from 'react';
import type { CMFApiResponse } from '../../types.js';

/**
 * Whether this is an installment (quota) purchase or a full one-time card charge.
 *
 * @example
 * ```ts
 * const mode: CMFPaymentMode = 'quotas'; // or 'normal'
 * ```
 */
export type CMFPaymentMode = 'quotas' | 'normal';

/**
 * Parameters for an installment (quota) purchase.
 * Requires a pre-selected plan from `useCMFQuotas`.
 *
 * @example
 * ```ts
 * const params: CMFQuotaPaymentParams = {
 *   mode: 'quotas',
 *   customerProductId: product.customerProductId,
 *   accountNumber: product.productAccount,
 *   uniqueCode: selectedPlan.uniqueCode,
 *   amount: 500,
 *   receiptNumber: `ORDER-${Date.now()}`,
 *   description: 'Purchase at My Store',
 *   userName: customer.email,
 * };
 * ```
 */
export interface CMFQuotaPaymentParams {
  /** Discriminator -- must be `'quotas'` */
  mode: 'quotas';
  /** Product UUID from `CMFProduct.customerProductId` */
  customerProductId: string;
  /** Encrypted account number from `CMFProduct.productAccount` */
  accountNumber: string;
  /** Selected plan's `uniqueCode` from `useCMFQuotas` */
  uniqueCode: string;
  /** Purchase amount in USD */
  amount: number;
  /** Unique receipt/order number generated by the merchant */
  receiptNumber: string;
  /** Purchase description shown in the CMF confirmation email */
  description: string;
  /** Customer username or identifier (typically the customer's email) */
  userName: string;
}

/**
 * Parameters for a normal (non-installment) one-time card purchase.
 *
 * @example
 * ```ts
 * const params: CMFNormalPaymentParams = {
 *   mode: 'normal',
 *   cardNumber: card.card,
 *   amount: 150.00,
 *   receiptNumber: `ORDER-${Date.now()}`,
 *   description: 'Purchase at My Store',
 *   userName: customer.email,
 * };
 * ```
 */
export interface CMFNormalPaymentParams {
  /** Discriminator -- must be `'normal'` */
  mode: 'normal';
  /** Encrypted card number from `CMFAccountCard.card` */
  cardNumber: string;
  /** Purchase amount in USD */
  amount: number;
  /** Unique receipt/order number generated by the merchant */
  receiptNumber: string;
  /** Purchase description shown in the CMF confirmation email */
  description: string;
  /** Customer username or identifier */
  userName: string;
}

/**
 * Union type for all CMF payment parameter shapes.
 *
 * @example
 * ```ts
 * const params: CMFPaymentParams = isInstallment
 *   ? { mode: 'quotas', ... }
 *   : { mode: 'normal', ... };
 * ```
 */
export type CMFPaymentParams = CMFQuotaPaymentParams | CMFNormalPaymentParams;

/**
 * Configuration options for `useCMFPayment`.
 *
 * @example
 * ```ts
 * const config: UseCMFPaymentConfig = {
 *   endpoint: '/api/cmf/pay',
 * };
 * ```
 */
export interface UseCMFPaymentConfig {
  /**
   * Backend endpoint for processing CMF payments.
   * The hook will POST the `CMFPaymentParams` object to this URL.
   *
   * Your backend should:
   * 1. Read `params.mode` to determine whether to call `processPurchaseInQuotas` or `processNormalPurchase`
   * 2. Call `CMFClient.ensureAuthenticated()` first
   * 3. Return the `CMFApiResponse` directly
   *
   * @default '/api/cmf/pay'
   */
  endpoint?: string;
}

/**
 * Return value of `useCMFPayment`.
 *
 * @example
 * ```ts
 * const { pay, isLoading, result, error, reset } = useCMFPayment();
 * ```
 */
export interface UseCMFPaymentReturn {
  /**
   * Process a CMF payment (installments or normal card charge).
   * Your backend calls `CMFClient.processPurchaseInQuotas` or `processNormalPurchase`.
   *
   * @example
   * ```ts
   * await pay({ mode: 'quotas', ... });
   * ```
   */
  pay: (params: CMFPaymentParams) => Promise<void>;
  /** True while the payment request is in flight. */
  isLoading: boolean;
  /** The successful payment response from CMF. `null` until a payment completes. */
  result: CMFApiResponse | null;
  /** Error message from the last failed payment, or `null` if none. */
  error: string | null;
  /** Reset result and error back to initial values. */
  reset: () => void;
}

/**
 * Executes a CMF payment -- either an installment (quota) purchase or a full card charge.
 *
 * The hook calls your backend, which processes the payment using `CMFClient`.
 * On success, CMF automatically sends a confirmation email to the customer.
 *
 * **Backend contract** -- your `/api/cmf/pay` endpoint must accept `CMFPaymentParams`
 * and return the `CMFApiResponse` from CMF directly. Use `params.mode` to branch:
 * - `mode: 'quotas'` -> call `CMFClient.processPurchaseInQuotas()`
 * - `mode: 'normal'` -> call `CMFClient.processNormalPurchase()`
 *
 * @param config - Hook configuration
 * @returns Payment state and the `pay` action
 *
 * @example
 * ```tsx
 * import { useCMFPayment } from '@panama-payments/cmf/react';
 *
 * function PaymentButton({ product, plan, customer, total }: Props) {
 *   const { pay, isLoading, result, error } = useCMFPayment();
 *
 *   const handlePay = async () => {
 *     await pay({
 *       mode: 'quotas',
 *       customerProductId: product.customerProductId,
 *       accountNumber: product.productAccount,
 *       uniqueCode: plan.uniqueCode,
 *       amount: total,
 *       receiptNumber: `ORDER-${Date.now()}`,
 *       description: 'Purchase at My Store',
 *       userName: customer.email,
 *     });
 *   };
 *
 *   if (result) return <p>Payment successful! Code: {result.uniqueCode}</p>;
 *
 *   return (
 *     <div>
 *       {error && <p>Error: {error}</p>}
 *       <button onClick={handlePay} disabled={isLoading}>
 *         {isLoading ? 'Processing...' : 'Pay with CMF'}
 *       </button>
 *     </div>
 *   );
 * }
 * ```
 */
export function useCMFPayment(config: UseCMFPaymentConfig = {}): UseCMFPaymentReturn {
  const endpoint = config.endpoint ?? '/api/cmf/pay';

  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<CMFApiResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const pay = useCallback(
    async (params: CMFPaymentParams) => {
      setIsLoading(true);
      setError(null);
      setResult(null);
      try {
        const res = await fetch(endpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(params),
        });
        if (!res.ok) {
          const err = (await res.json().catch(() => ({}))) as { message?: string };
          throw new Error(err.message ?? `Payment failed with status ${res.status}`);
        }
        const data = (await res.json()) as CMFApiResponse;
        setResult(data);
      } catch (e) {
        setError(e instanceof Error ? e.message : 'Payment failed');
      } finally {
        setIsLoading(false);
      }
    },
    [endpoint],
  );

  const reset = useCallback(() => {
    setResult(null);
    setError(null);
  }, []);

  return { pay, isLoading, result, error, reset };
}
